apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  username: {{ .Values.mongodb.username | b64enc }}
  password: {{ .Values.mongodb.password | b64enc }}
  uri: {{ .Values.mongodb.uri | b64enc }}
